import styled from '@emotion/styled';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import TwitterIcon from '@mui/icons-material/Twitter';
import HomeIcon from '@mui/icons-material/Home';

type Props = Readonly<{ className?: string }>;

const Page: NextPage<Props> = ({ className }) => (
  <div {...{ className }}>
    <Head>
      <title>Create Next App</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
    <main className='vertical flex'>
      <Link href='/search'>
        <div className='button'>プラグイン検索</div>
      </Link>
      <div>Created by Ribbit</div>
      <div className='flex'>
        <Link href={`https://ribbit.work`}>
          <a target='_blank' rel='noreferrer'>
            <HomeIcon />
          </a>
        </Link>
        <Link href={`https://twitter.com/LbRibbit`}>
          <a target='_blank' rel='noreferrer'>
            <TwitterIcon />
          </a>
        </Link>
      </div>
      <div className='vertical flex powerdby'>
        <div>Powerd by</div>
        <div className='flex'>
          <Link href='https://nextjs.org/'>Next.js</Link>
          <Link href='https://vercel.com/'>Vercel</Link>
        </div>
      </div>
    </main>
  </div>
);

const StyledPage = styled(Page)`
  display: flex;
  justify-content: center;
  align-items: center;
  color: #819baa;

  main {
  }

  .flex {
    display: flex;
    justify-content: center;
    align-items: center;
    gap: 16px;
  }

  .vertical {
    flex-direction: column;
  }

  .powerdby {
    gap: 8px;
  }

  min-height: 100vh;

  .button {
    transition: all 250ms ease;
    box-shadow: 0 1px 2px -1px #3573, 0 2px 4px 1px #3572;
    &:hover {
      box-shadow: 0 3px 5px -2px #3573, 0 3px 8px -1px #3575;
    }
    border-radius: 4px;
    padding: 12px 24px;
    cursor: pointer;
  }

  a {
    color: #1976d2;
  }
`;

export default StyledPage;
